import { createFileRoute } from "@tanstack/react-router";
import { timingSafeEqual } from "crypto";

/**
 * Registers a video made OUTSIDE the website pipeline (e.g. generated by the
 * studio assistant in chat/WhatsApp) into the website's video history, so it
 * shows up on the Videos page for review, approval and publishing like any
 * other finished video.
 *
 * Multipart form fields: title (required), topic (optional), description
 * (optional), file (required, the finished MP4, <= 100 MB).
 * Auth: header `x-worker-secret` must match `worker_secret` in internal_config
 * (falls back to `cron_secret`).
 *
 * The owner is resolved server-side: the first admin in user_roles, falling
 * back to the most recent project owner. user_id is ALWAYS written explicitly
 * so RLS (user_id = auth.uid()) returns the rows to the owner.
 */

const BUCKET = "videos";

export const Route = createFileRoute("/api/public/hooks/video-chat-delivery")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const { supabaseAdmin: db } = await import("@/integrations/supabase/client.server");
        const { data: rows } = await db.from("internal_config").select("key, value").in("key", ["worker_secret", "cron_secret"]);
        const want = rows?.find((r: any) => r.key === "worker_secret")?.value ?? rows?.find((r: any) => r.key === "cron_secret")?.value ?? "";
        const got = Buffer.from(request.headers.get("x-worker-secret") ?? "");
        const wantBuf = Buffer.from(want);
        if (!wantBuf.length || got.length !== wantBuf.length || !timingSafeEqual(got, wantBuf)) {
          return new Response("Unauthorized", { status: 401 });
        }

        const form = await request.formData().catch(() => null);
        const title = form?.get("title");
        const topic = form?.get("topic");
        const description = form?.get("description");
        const file = form?.get("file");
        if (typeof title !== "string" || !title.trim() || !(file instanceof File)) {
          return Response.json({ ok: false, error: "Expected multipart fields: title, file (MP4)." }, { status: 400 });
        }
        const bytes = new Uint8Array(await file.arrayBuffer());
        if (!bytes.length || bytes.length > 100 * 1024 * 1024) {
          return Response.json({ ok: false, error: "File is empty or larger than 100 MB." }, { status: 400 });
        }

        // Resolve the studio owner: first admin, else the most recent project owner.
        let ownerId: string | null = null;
        const { data: admins } = await db.from("user_roles").select("user_id").eq("role", "admin").limit(1);
        ownerId = (admins as any[])?.[0]?.user_id ?? null;
        if (!ownerId) {
          const { data: recent } = await db.from("projects").select("user_id").order("created_at", { ascending: false }).limit(1);
          ownerId = (recent as any[])?.[0]?.user_id ?? null;
        }
        if (!ownerId) return Response.json({ ok: false, error: "No studio user found to own this video." }, { status: 400 });

        const now = new Date().toISOString();
        const { data: project, error: projErr } = await db.from("projects").insert({
          user_id: ownerId,
          title: title.trim().slice(0, 200),
          idea: (typeof description === "string" && description.trim() ? description.trim() : title.trim()).slice(0, 4000),
          topic: typeof topic === "string" && topic.trim() ? topic.trim().slice(0, 200) : null,
          target_duration_seconds: 30,
          aspect_ratio: "9:16",
          target_platform: "TikTok",
          language: "English",
          status: "COMPLETED",
          current_stage: "metadata",
          reference_notes: "Made in chat — delivered by the studio assistant.",
        }).select("id").single();
        if (projErr || !project) return Response.json({ ok: false, error: `Could not create project: ${projErr?.message}` }, { status: 500 });

        // Store the MP4 in the site's own bucket.
        const safeName = (file.name || "chat-video.mp4").replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 80);
        const path = `${project.id}/${Date.now()}-${safeName}`;
        let { error } = await db.storage.from(BUCKET).upload(path, bytes, { contentType: file.type || "video/mp4", upsert: false });
        if (error && /bucket not found/i.test(error.message)) {
          const { error: mkErr } = await db.storage.createBucket(BUCKET, { public: true });
          if (mkErr) return Response.json({ ok: false, error: `Could not create storage bucket: ${mkErr.message}` }, { status: 500 });
          ({ error } = await db.storage.from(BUCKET).upload(path, bytes, { contentType: file.type || "video/mp4", upsert: false }));
        }
        if (error) return Response.json({ ok: false, error: `Upload failed: ${error.message}` }, { status: 500 });
        const { data: pub } = db.storage.from(BUCKET).getPublicUrl(path);
        const url: string = pub.publicUrl;

        await db.from("video_assets").insert({ project_id: project.id, user_id: ownerId, kind: "final", url, metadata: { source: "chat" } });
        const { data: videoRow } = await db.from("videos").insert({
          project_id: project.id, user_id: ownerId, provider: "chat-assistant", status: "done", video_url: url,
        }).select("id").single();
        await db.from("production_history").insert({ project_id: project.id, action: "Video delivered from chat", detail: title.trim().slice(0, 200) });

        const { logActivity } = await import("@/lib/jobs/jobs.server");
        await logActivity({ userId: ownerId, category: "production", level: "success", projectId: project.id, event: "Video finished — ready for review", detail: title.trim().slice(0, 200) });

        return Response.json({ ok: true, projectId: project.id, videoId: videoRow?.id ?? null, url });
      },
    },
  },
});
