/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCharactersRouteImport } from './routes/_authenticated/characters'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedSchedulerRouteImport } from './routes/_authenticated/scheduler'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedStoryboardsRouteImport } from './routes/_authenticated/storyboards'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedAnalyticsPostIdRouteImport } from './routes/_authenticated/analytics.$postId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedWorkspaceProjectIdRouteImport } from './routes/_authenticated/workspace.$projectId'
import { Route as ApiPublicHooksPublishDueRouteImport } from './routes/api/public/hooks/publish-due'
import { Route as ApiPublicHooksSyncAnalyticsRouteImport } from './routes/api/public/hooks/sync-analytics'
import { Route as ApiPublicOauthPlatformCallbackRouteImport } from './routes/api/public/oauth.$platform.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharactersRoute = AuthenticatedCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulerRoute = AuthenticatedSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryboardsRoute =
  AuthenticatedStoryboardsRouteImport.update({
    id: '/storyboards',
    path: '/storyboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsPostIdRoute =
  AuthenticatedAnalyticsPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceProjectIdRoute =
  AuthenticatedWorkspaceProjectIdRouteImport.update({
    id: '/workspace/$projectId',
    path: '/workspace/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPublishDueRoute =
  ApiPublicHooksPublishDueRouteImport.update({
    id: '/api/public/hooks/publish-due',
    path: '/api/public/hooks/publish-due',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncAnalyticsRoute =
  ApiPublicHooksSyncAnalyticsRouteImport.update({
    id: '/api/public/hooks/sync-analytics',
    path: '/api/public/hooks/sync-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthPlatformCallbackRoute =
  ApiPublicOauthPlatformCallbackRouteImport.update({
    id: '/api/public/oauth/$platform/callback',
    path: '/api/public/oauth/$platform/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/storyboards': typeof AuthenticatedStoryboardsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/analytics/$postId': typeof AuthenticatedAnalyticsPostIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/workspace/$projectId': typeof AuthenticatedWorkspaceProjectIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/hooks/sync-analytics': typeof ApiPublicHooksSyncAnalyticsRoute
  '/api/public/oauth/$platform/callback': typeof ApiPublicOauthPlatformCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/storyboards': typeof AuthenticatedStoryboardsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/analytics/$postId': typeof AuthenticatedAnalyticsPostIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/workspace/$projectId': typeof AuthenticatedWorkspaceProjectIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/hooks/sync-analytics': typeof ApiPublicHooksSyncAnalyticsRoute
  '/api/public/oauth/$platform/callback': typeof ApiPublicOauthPlatformCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/characters': typeof AuthenticatedCharactersRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/storyboards': typeof AuthenticatedStoryboardsRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/analytics/$postId': typeof AuthenticatedAnalyticsPostIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/workspace/$projectId': typeof AuthenticatedWorkspaceProjectIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/hooks/sync-analytics': typeof ApiPublicHooksSyncAnalyticsRoute
  '/api/public/oauth/$platform/callback': typeof ApiPublicOauthPlatformCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/characters'
    | '/create'
    | '/dashboard'
    | '/providers'
    | '/scheduler'
    | '/settings'
    | '/skills'
    | '/social'
    | '/storyboards'
    | '/videos'
    | '/analytics/$postId'
    | '/projects/$projectId'
    | '/workspace/$projectId'
    | '/projects/'
    | '/api/public/hooks/publish-due'
    | '/api/public/hooks/sync-analytics'
    | '/api/public/oauth/$platform/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/calendar'
    | '/characters'
    | '/create'
    | '/dashboard'
    | '/providers'
    | '/scheduler'
    | '/settings'
    | '/skills'
    | '/social'
    | '/storyboards'
    | '/videos'
    | '/analytics/$postId'
    | '/projects/$projectId'
    | '/workspace/$projectId'
    | '/projects'
    | '/api/public/hooks/publish-due'
    | '/api/public/hooks/sync-analytics'
    | '/api/public/oauth/$platform/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/characters'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/providers'
    | '/_authenticated/scheduler'
    | '/_authenticated/settings'
    | '/_authenticated/skills'
    | '/_authenticated/social'
    | '/_authenticated/storyboards'
    | '/_authenticated/videos'
    | '/_authenticated/analytics/$postId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/workspace/$projectId'
    | '/_authenticated/projects/'
    | '/api/public/hooks/publish-due'
    | '/api/public/hooks/sync-analytics'
    | '/api/public/oauth/$platform/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksPublishDueRoute: typeof ApiPublicHooksPublishDueRoute
  ApiPublicHooksSyncAnalyticsRoute: typeof ApiPublicHooksSyncAnalyticsRoute
  ApiPublicOauthPlatformCallbackRoute: typeof ApiPublicOauthPlatformCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters': {
      id: '/_authenticated/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AuthenticatedCharactersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboards': {
      id: '/_authenticated/storyboards'
      path: '/storyboards'
      fullPath: '/storyboards'
      preLoaderRoute: typeof AuthenticatedStoryboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/$postId': {
      id: '/_authenticated/analytics/$postId'
      path: '/$postId'
      fullPath: '/analytics/$postId'
      preLoaderRoute: typeof AuthenticatedAnalyticsPostIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$projectId': {
      id: '/_authenticated/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspaceProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/publish-due': {
      id: '/api/public/hooks/publish-due'
      path: '/api/public/hooks/publish-due'
      fullPath: '/api/public/hooks/publish-due'
      preLoaderRoute: typeof ApiPublicHooksPublishDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-analytics': {
      id: '/api/public/hooks/sync-analytics'
      path: '/api/public/hooks/sync-analytics'
      fullPath: '/api/public/hooks/sync-analytics'
      preLoaderRoute: typeof ApiPublicHooksSyncAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/$platform/callback': {
      id: '/api/public/oauth/$platform/callback'
      path: '/api/public/oauth/$platform/callback'
      fullPath: '/api/public/oauth/$platform/callback'
      preLoaderRoute: typeof ApiPublicOauthPlatformCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsPostIdRoute: typeof AuthenticatedAnalyticsPostIdRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsPostIdRoute: AuthenticatedAnalyticsPostIdRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCharactersRoute: typeof AuthenticatedCharactersRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedSchedulerRoute: typeof AuthenticatedSchedulerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedStoryboardsRoute: typeof AuthenticatedStoryboardsRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedWorkspaceProjectIdRoute: typeof AuthenticatedWorkspaceProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCharactersRoute: AuthenticatedCharactersRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedSchedulerRoute: AuthenticatedSchedulerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedStoryboardsRoute: AuthenticatedStoryboardsRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedWorkspaceProjectIdRoute: AuthenticatedWorkspaceProjectIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksPublishDueRoute: ApiPublicHooksPublishDueRoute,
  ApiPublicHooksSyncAnalyticsRoute: ApiPublicHooksSyncAnalyticsRoute,
  ApiPublicOauthPlatformCallbackRoute: ApiPublicOauthPlatformCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
